### ISSUE TITLE
Getting segmentation fault after last update

### ISSUE THREAD

**Issue by arthurnevesbefore** [escapingnetwork/core-keeper-dedicated#17]
core-core-keeper-1  | Success! App '1007' already up to date.
core-core-keeper-1  | Success! App '1963720' already up to date.
core-core-keeper-1  | Started server process with pid 117
core-core-keeper-1  | _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
core-core-keeper-1  | [UnityMemory] Configuration Parameters - Can be set up in boot.config
core-core-keeper-1  |     "memorysetup-bucket-allocator-granularity=16"
core-core-keeper-1  |     "memorysetup-bucket-allocator-bucket-count=8"
core-core-keeper-1  |     "memorysetup-bucket-allocator-block-size=4194304"
core-core-keeper-1  |     "memorysetup-bucket-allocator-block-count=1"
core-core-keeper-1  |     "memorysetup-main-allocator-block-size=16777216"
core-core-keeper-1  |     "memorysetup-thread-allocator-block-size=16777216"
core-core-keeper-1  |     "memorysetup-gfx-main-allocator-block-size=16777216"
core-core-keeper-1  |     "memorysetup-gfx-thread-allocator-block-size=16777216"
core-core-keeper-1  |     "memorysetup-cache-allocator-block-size=4194304"
core-core-keeper-1  |     "memorysetup-typetree-allocator-block-size=2097152"
core-core-keeper-1  |     "memorysetup-profiler-bucket-allocator-granularity=16"
core-core-keeper-1  |     "memorysetup-profiler-bucket-allocator-bucket-count=8"
core-core-keeper-1  |     "memorysetup-profiler-bucket-allocator-block-size=4194304"
core-core-keeper-1  |     "memorysetup-profiler-bucket-allocator-block-count=1"
core-core-keeper-1  |     "memorysetup-profiler-allocator-block-size=16777216"
core-core-keeper-1  |     "memorysetup-profiler-editor-allocator-block-size=1048576"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-main=4194304"
core-core-keeper-1  |     "memorysetup-job-temp-allocator-block-size=2097152"
core-core-keeper-1  |     "memorysetup-job-temp-allocator-block-size-background=1048576"
core-core-keeper-1  |     "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-background-worker=32768"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-job-worker=262144"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-preload-manager=262144"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-audio-worker=65536"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-cloud-worker=32768"
core-core-keeper-1  |     "memorysetup-temp-allocator-size-gfx=262144"
core-core-keeper-1  | ./launch.sh: line 46:   117 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer -batchmode -logfile -world "${WORLD_INDEX}" -worldname "${WORLD_NAME}" -worldseed "${WORLD_SEED}" -gameid "${GAME_ID}" -datapath "${STEAMAPPDATADIR}" -maxplayers "${MAX_PLAYERS}" -logfile CoreKeeperServerLog.txt

**Comment by arthurnevesbefore** [comment]
Got it fixed installing gnome-terminal. Some lib there fixed the issue.

**Comment by xcjs** [comment]
It sounds like there's potentially an issue with where the Steam SDK runtime is installed in relation to the server path based on the comment here:

https://steamcommunity.com/app/1621690/discussions/0/3759978783504303058/#c3759979237848764800

I'm not sure what the default install location is supposed to be, so I can't tell if this helps.

**Comment by appletalk** [comment]
I narrowed it down to a single required package the libxi6.  `apt install libxi6` allowed the dedicated server run for me using https://gitlab.com/tedtramonte/core-keeper-server

**Comment by xcjs** [comment]
> I narrowed it down to a single required package the libxi6. `apt install libxi6` allowed the dedicated server run for me using https://gitlab.com/tedtramonte/core-keeper-server

Nice leg work! I submitted a PR here to fix the issue: https://github.com/escapingnetwork/core-keeper-dedicated/pull/18

**Comment by arguser** [comment]
Thanks everyone, sorry I've been off. All PRs merged!
