### ISSUE TITLE
docker-image not updated with fix from #17

### ISSUE THREAD

**Issue by anpross** [escapingnetwork/core-keeper-dedicated#19]
first: thanks for your efforts providing this.

when setting up a game-server, I found the same issue that was described in issue #17. Then building the docker image locally and using that solved the issue.

When checking the Containerfile content on docker-hub, i don't see the libxi6 dependency that was added to fix the issue.

my issue is fixed but i thought i let you know.

**Comment by Bloodsnake** [comment]
Can confirm, had the same issue and building the image locally fixed it for me too.

**Comment by arguser** [comment]
Probably something went wrong in CI, just pushed an image, hopefully it's solved now. https://hub.docker.com/r/escaping/core-keeper-dedicated/tags
