### ISSUE TITLE
Server won't save

### ISSUE THREAD

**Issue by FhenrisGit** [escapingnetwork/core-keeper-dedicated#28]
I have an issue with the server not saving worlds and just reseting everytime I'm restarting the server.

Here are the steps I followed :

First I have to tell I'm on a TrueNAS Scale server

I created Datasets
![01](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/f00e8303-1b80-4289-89ac-56806e915978)

Gave root permissions
![02](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/49d2d52c-f6a8-410b-92ec-3f02a4ecaf4b)

Then launched the Docker image with basic configuration
![03](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/d9a2e0cb-89a0-4546-853c-3f00b8d5e764)

Created the volumes for persistent storage
![04](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/8fb44260-e3ed-42a1-8892-05fe66c63195)

Then I launched it and volume server-files filed
![05](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/1ec1432a-29dc-445e-9571-976100d0edd6)

In the Shell 
![06](https://github.com/escapingnetwork/core-keeper-dedicated/assets/139649040/48190bab-f569-4b4b-8b6b-bd3b48aeb79d)

If I get the GameID from the txt I can join the game, friends can join, and things work fine.

I wait for 10-15 minutes

But the server never creates any "worlds" folder or 0.world.gzip file.

So if I restart the server, my world is lost and the server creates a new one.

**Comment by arguser** [comment]
@FhenrisGit I have no experience with TrueNAS but shouldn't be much different, can you share the logs from when you boot the image?

**Comment by Micke90s** [comment]
Just tried the curent case.
If the environment variable "DATA_PATH" is not set the savegame will be located under.
`/home/steam/.config/Pugstorm/Core Keeper/DedicatedServer`  
As this is not part of your volumes the files may be lost

**Comment by FhenrisGit** [comment]
> Just tried the curent case. If the environment variable "DATA_PATH" is not set the savegame will be located under. `/home/steam/.config/Pugstorm/Core Keeper/DedicatedServer` As this is not part of your volumes the files may be lost

that's exactly what fixed it, I set the DATA_PATH to /home/steam/core-keeper-data and it worked !

Could be a good thing to add this to the installation guide if someone else has this issue ?

**Comment by arguser** [comment]
@FhenrisGit @Micke90s quick fix at https://github.com/escapingnetwork/core-keeper-dedicated/pull/29, hopefully the env-var resolves fine.

**Comment by FhenrisGit** [comment]
I have a hard time making it to work a second time... Don't know why, launched another docker image, new dedicated volume for share host path volumes, and everything just like in the screenshots, no env var set. But this time core-keeper-dedicated is empty, can't get the GameID.txt. Don't know if there's some kind of conflict between my previous pull and the second, I'm really new to docker, started only yesterday so I don't think I can help troubleshooting things, I managed to make it work and don't want to mess everything now x)

**Comment by FhenrisGit** [comment]
@arguser I don't know how, but I think the latest version destroyed my working server. How can I pull to the latest version before last ? I think it's better to keep things how they were, just make it clear in tutorial that env var DATA_PATH should be set

**Comment by Micke90s** [comment]
@FhenrisGit I tried the latest build and everything worked fine. Only the download of the steam data took very long this time. May the steam servers are a bit slow at the moment.

**Comment by arguser** [comment]
@FhenrisGit at the moment I'm not keeping versions, you probably have a previous image locally. Still, I'm correctly seeing the env being set on https://hub.docker.com/layers/escaping/core-keeper-dedicated/latest/images/sha256-b6fa8ad55608eceb14cc9dac1e5da4da6b3f16f5bd35af66a64f40a25e86ca38?context=explore

The latest version didn't have any changes regarding core-keeper-dedicated folder, so be sure double check your settings.
