### ISSUE TITLE
Server crash - Segmentation faul

### ISSUE THREAD

**Issue by Kogs** [escapingnetwork/core-keeper-dedicated#53]
Hey starting today our server started crashing.

There isn't much in the log, only this.
``
./launch.sh: line 97:    86 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer "${params[@]}"
``

[worlds.zip](https://github.com/user-attachments/files/16913590/worlds.zip)

If you need any more information, feel free to let me know.

**Comment by Makerblaker** [comment]
Can you attach the `CoreKeeperLog.txt `located in the `~/core-keeper-dedicated/` folder?

**Comment by Kogs** [comment]
There is no stack trace in there. I guess it was overwritten instantly because the server restarted on its own.
Maybe its still useful: 
[CoreKeeperServerLog.txt](https://github.com/user-attachments/files/16913885/CoreKeeperServerLog.txt)

Is there a place where the previous log is stored? I couldn't find anything.

**Comment by Makerblaker** [comment]
Not that I am aware of. When the server starts, it overwrites the file. This is the behaviour of Core Keeper, not Docker.

**Comment by mattsepela** [comment]
FWIW, I changed the discord env variable in the config to 0 and it started up properly. When I had this on, it caused the segfault.

**Comment by Kogs** [comment]
It starts just fine. Discord integration is already disabled. 
I'll keep an eye out if it crashes again maybe I can get the log. But I think it is not related to docker here and is probably just a bug in the game.

**Comment by defib** [comment]
I am having the same issue, but setting DISCORD=0 did not fix it

**Comment by Makerblaker** [comment]
> I am having the same issue, but setting DISCORD=0 did not fix it

Could you send a copy of your CoreKeeperServerLog.txt?

**Comment by salkz** [comment]
```
couldn't initialize discord SDK: Ok InternalError
```

**Comment by Mok-sea** [comment]
> I am having the same issue, but setting DISCORD=0 did not fix it

Same here.

[_corekeeper-core-keeper-1_logs.txt](https://github.com/user-attachments/files/16950331/_corekeeper-core-keeper-1_logs.txt)
[CoreKeeperServerLog.txt](https://github.com/user-attachments/files/16950336/CoreKeeperServerLog.txt)

**Comment by CooperWallace** [comment]
I had issues with this when trying to mount specific folders within the container. Certain paths worked, and other's didnt.

**Comment by dvchdbfhjd** [comment]
Is there a solution to this problem? I set DISCORD=0 and that didn't solve the problem
Could this be a problem with the image system version?
I looked at CoreKeeperServerLog.txt, which says NullReferenceException and Signal 11, and CoreKeeperServer has no missing dependencies.

**Comment by Makerblaker** [comment]
> Is there a solution to this problem? I set DISCORD=0 and that didn't solve the problem Could this be a problem with the image system version? I looked at CoreKeeperServerLog.txt, which says NullReferenceException and Signal 11, and CoreKeeperServer has no missing dependencies.

Can you pull down a fresh image? Core-Keeper did release an update that required a rebuild of the container.

**Comment by Write** [comment]
Hello same here :( Linux headless on debian 12

**Comment by Write** [comment]
I finally managed to use the container, but I'm forced to use volumes and can't bind to real file system directories. For example using `- ./data:/home/steam/core-keeper-data` is not possible and would make the server segfault as it can't find world data.

**Comment by Micke90s** [comment]
@Write Sounds like a problem of the file authorisation on the host system. Could you please check the owner of the directory `./data` using `ls -lisa` on the host?

**Comment by Write** [comment]
> @Write Sounds like a problem of the file authorisation on the host system. Could you please check the owner of the directory `./data` using `ls -lisa` on the host?

Owner is "'ubuntu" which is user 1000 on my host. 

User steam inside the container is user 1000.

Doing docker exec -it --user=steam corekeeper-core-keeper-1 /bin/bash -c 'touch ~/core-keeper-data/test' does work and indicate that user steam can indeed write to the directory as the file appears on host.

**Comment by Write** [comment]
Other than that, using only volumes right now.
Played one hour or so, and I also have the Segfault issue now.

corekeeper  | ./launch.sh: line 12:    81 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer "${params[@]}"

**Comment by sirsikes777** [comment]
I have been trying to get a linux server spun up for core keeper for the past 5 hours with several different methods, still can't get it to work on ubuntu even with this docker image. Seg fault "ck-server kernel: [ 4219.550173] CoreKeeperServe[26747]: segfault at 0 ip 000000004121a756 sp 00007ffc7c303dc0 error 4 likely on CPU 0 (core 0, socket 0)"

**Comment by sdedovic** [comment]
The problem for me was permissions on the mounted volume (`-v` flag for docker).

The user inside the container, by default, is `steam` with the UID and GUID of `1000`. In my case, I had to

```
chown 1000:1000 /var/game-data/corekeeper
``` 

in order to run the container with
```
docker run ... -v /var/game-data/corekeeper:/home/steam/core-keeper-data ...
```

**Comment by nyxi** [comment]
For me the problem was trying to use `SERVER_IP` and `SERVER_PORT`:

```
SERVER_IP=<my-ip-address>
SERVER_PORT=15000
```

Reverting this to empty values fixed the issue with segfaults:

```
SERVER_IP=
SERVER_PORT=
```
