### ISSUE TITLE
Question regarding the Discord Format String

### ISSUE THREAD

**Issue by Heduardocp** [escapingnetwork/core-keeper-dedicated#56]
Hello! is there any guide or source i can use to understand how to format the discord message? i am getting the message correctly to the discord but i can only add text in a very basic format like "Hello world %s". Is there any way i can create more interesting formats like extra lines, paragraphs or emojis?

**Comment by arguser** [comment]
It uses printf, please refer to printf documentation or any related article such as https://linuxize.com/post/bash-printf-command/
