### ISSUE TITLE
World data does not save to /home/steam/core-keeper-data by default

### ISSUE THREAD

**Issue by wgbartley** [escapingnetwork/core-keeper-dedicated#57]
I'm not sure where it saves by default, but the `/home/steam/core-keeper-data` directory remained empty no matter what I specified in `docker-compose.yml` volumes.

It seems that if the `DATA_PATH` value in core.env is left empty, that parameter is not passed to the game launcher in `launch.sh`.  Once I set `DATA_PATH=/home/steam/core-keeper-data` in core.env, the world data finally saved to that path.

**Comment by Micke90s** [comment]
Yes, we already had the problem in issue #50 
(see https://github.com/escapingnetwork/core-keeper-dedicated/issues/50#issuecomment-2333991650)
If `DATA_PATH` is defined it overrides the default value. If the set value is initial the `CoreKeeperServer` uses the default path `/home/steam/.config/Pugstorm/Core Keeper/DedicatedServer`
