### ISSUE TITLE
Unable to get any halloween items.

### ISSUE THREAD

**Issue by IcelandicIcecream** [escapingnetwork/core-keeper-dedicated#65]
Any halloween items can be picked up but it doesn't show up in my inventory. Not sure whether it has anything to do with the server but just putting this out here.

**Comment by Diyagi** [comment]
This usually happens when you set your game season to halloween but not the server.

**Comment by EmberKnight** [comment]
I have the same issue as well. The parameter value -1 for seasons doesn't work as described. According to the wiki -1 is None https://core-keeper.fandom.com/wiki/Server_Config

When setting the value to the actual season (e.g. 2 for Halloween) it works without a problem.

Something seems off here

**Comment by Micke90s** [comment]
@EmberKnight Are you sure? I would guess that the wiki is outdated. 

The seasons are defined as `Enum`. This should start at `0`.  So the README should be correct:
![image](https://github.com/user-attachments/assets/685c0595-4ce0-4a2b-a6ed-bfc0b793d2a4)
(Source Pug.Base.dll)

**Comment by EmberKnight** [comment]
@Micke90s  this is from the README

https://github.com/escapingnetwork/core-keeper-dedicated

SEASON              Overrides current season by setting to any of None (0), Easter (1), Halloween (2), Christmas (3), Valentine (4), Anniversary (5), CherryBlossom (6), LunarNewYear(7). -1 is default setting where it is set depending on system date.

**Comment by Micke90s** [comment]
> SEASON Overrides current season by setting to any of None (0), Easter (1), Halloween (2), Christmas (3), Valentine (4), Anniversary (5), CherryBlossom (6), LunarNewYear(7). -1 is default setting where it is set depending on system date.

Yes, this is a copy of the official `README`which is part of the DedicatedServer and this should be correct. 
 
I just tried it and you are correct and it did not work. I don’t think that the value of  `-1` is wrong. I rather believe that there is a problem on the supply of the value. May the value `-1` is handled as a parameter which would cause that the parameter `-season` to get the value ` `. This may could be parsed as `0`.

**Comment by Micke90s** [comment]
I think I found the problem. Season `-1` must not be supplied.
Based on the log of my server `Forcing season -1` it should be the following problem.
![image](https://github.com/user-attachments/assets/02b9896a-2954-4722-b3ed-e7a7068e30ce)
If the `-season` parameter is present the DedicatedServer will not call `CalculateSeason` which seems to cause the same behaviour as `None`.

**Comment by EmberKnight** [comment]
So just leave Season variable empty or just omit it altogether?

**Comment by Micke90s** [comment]
Technical it is a bug in the DedicatedServer application which we use. I will open a bug report on @Pugstorm webpage. I just  verified this on my local system. (Windows host) 

@arguser May we should remove the default values as these values should be set by the DedicatedServer itself. Maybe @Diyagi could add this to #62.  So, the problem only would occur if the `-season` parameter is set in the environment variables.

**Comment by IcelandicIcecream** [comment]
> So just leaving Season variable empty or just omitting it altogether would work?

You need to explicitly set it at halloween for it work. omitting doesn't work, not sure if having empty works but i'm assuming it doesn't

**Comment by Diyagi** [comment]
> Technical it is a bug in the DedicatedServer application which we use. I will open a bug report on @Pugstorm webpage. I just verified this on my local system. (Windows host)
> 
> @arguser May we should remove the default values as these values should be set by the DedicatedServer itself. Maybe @Diyagi could add this to #62. So, the problem only would occur if the `-season` parameter is set in the environment variables.

Already did



> > So just leaving Season variable empty or just omitting it altogether would work?
> 
> You need to explicitly set it at halloween for it work. omitting doesn't work, not sure if having empty works but i'm assuming it doesn't

Setting it to SEASON="" should work
`if [ ! -z "${SEASON}" ]; then params=( "${params[@]}" -season "${SEASON}" ); fi`

**Comment by Micke90s** [comment]
@Diyagi  Thank you. I missed that. I thought the default value was still `-1`
