### ISSUE TITLE
Missing libraries in Raspberry Pi 4

### ISSUE THREAD

**Issue by RubenPineda** [escapingnetwork/core-keeper-dedicated#75]
I am trying to run the CoreKeeper server on my Raspberry Pi 4, but it seems there is some kind of error. I am attaching the log.

[Log.txt](https://github.com/user-attachments/files/17985993/Log.txt)

**Comment by Micke90s** [comment]
Raspberry PI 4 will not work.
See the comment of @feserr at https://github.com/escapingnetwork/core-keeper-dedicated/pull/73#issuecomment-2508940289
> The ARM64 image that is uses is only compatible with Raspberry Pi 5 as mention here: https://github.com/sonroyaalmerol/steamcmd-arm64?tab=readme-ov-file#box64-builds

I had the same problem during my test implementation

**Comment by RubenPineda** [comment]
I see... so there's no way to make it work? Thank you anyway!

**Comment by feserr** [comment]
Maybe it is possible. The image https://github.com/sonroyaalmerol/steamcmd-arm64 has to be updated to support more platforms. I have had a look at BOX64 and it supports RPI3 and RPI4.

I have forked the repo `sonroyaalmerol/steamcmd-arm64` and made the changes to support RPI3 and RPI4, however, I am still building it and if succeeded, I can only test on a RPI3 as I don't have a RPI4. The fork is here, you can test it with a RPI4: https://github.com/feserr/steamcmd-arm64

For building:
```bash
$ docker build -t sonroyaalmerol/steamcmd-arm64 --file=bookworm/Dockerfile .
```

**Comment by RubenPineda** [comment]
Oh, that's good news. I can test it for you (and for me), but I'm afraid I'm gonna need a step by step guide on how to do so, since I have zero experience with linux or docker. Do I have to navigate to the directory where docker-compose.yml is and then use the commando you provided? And do I have to do something with the fork?

Thank you so much in advance for your time and effort.

**Comment by feserr** [comment]
> Oh, that's good news. I can test it for you (and for me), but I'm afraid I'm gonna need a step by step guide on how to do so, since I have zero experience with linux or docker. Do I have to navigate to the directory where docker-compose.yml is and then use the command you provided? And do I have to do something with the fork?
> 
> Thank you so much in advance for your time and effort.

Don't worry then, you will need to do multiples of steps, modifying files. Doing one wrong will mess up with everything. If RPI3 work it "should" work on RPI4.

**Comment by RubenPineda** [comment]
In that case, what should I do to get the server up and running? Should I get inside the docker container and install/update your fork? Sorry for the inconvenience...

Again, thank you for your time.

**Comment by feserr** [comment]
Seems the maintainer of the `steamcmd-arm64` has read of minds because they added support for RPI3 and RPI4 a few hours ago. Just hours before I was going to push a PR.

I have created a PR to use the new image.

**Comment by RubenPineda** [comment]
Hello again! Ty for your time and effort on this, I really appreciate it.

I've tried the new image, but something doesn't seem to work, maybe because I did something wrong (?). Here's the log if anyone can take a look at it.

Thanks in advance!

[Log.txt](https://github.com/user-attachments/files/18059944/Log.txt)

**Comment by feserr** [comment]
@RubenPineda That is a normal log, no errors there. What isn't working?

**Comment by RubenPineda** [comment]
@feserr  I have created docker-compose.yml and override.env (changing the device to rpi4), but seems like GameID.txt does not exist (or I'm unable to find it).

**Comment by feserr** [comment]
@RubenPineda I recommend to use mount bind folder instead of volume as the example says. For that you need to create this two folders where the `docker-compose.yml`file is:
```shell
mkdir -p server-files server-data
```

Then check which is your user and group by:
```shell
id -u # user ID
id -g # group ID
```

Add to `override.env` which user and group to use with the previous values, for example if boths are 1000:
```
PUID=1000
PGID=1000
```

Last but not least, modify the `docker-compose.yml`file to by like this:

```yaml
services:
  core-keeper:
    container_name: core-keeper-dedicated
    image: escaping/core-keeper-dedicated
    ports:
      - "$SERVER_PORT:$SERVER_PORT/udp"
    volumes:
      - ./server-files:/home/steam/core-keeper-dedicated
      - ./server-data:/home/steam/core-keeper-data
    env_file:
      - path: override.env
        required: false
    restart: unless-stopped
    stop_grace_period: 2m
```

The change is remove the bottom "volumes" configuration and changing the "volumes" of "core-keeper" configuration so it uses the local folder instead the volume ones.

Run the `up` again:
```shell
docker compose up -d
```

When the server is up, you can check the ID running:
```shell
cat server-files/GameID.txt
```

**Comment by RubenPineda** [comment]
@feserr First of all, thank you for your time. Now, it seems that its stuck in a loop. I'm getting things like

`core-keeper-dedicated  | /home/steam/scripts/launch.sh: line 10: kill: (123) - No such process
core-keeper-dedicated  | /home/steam/scripts/helper-functions.sh: line 58: wait: `': not a pid or valid job spec`

and

`core-keeper-dedicated  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
core-keeper-dedicated  | Steam API initialized
core-keeper-dedicated  | Steam server API failed to log in anonymously
core-keeper-dedicated  | Thread "CHTTPClientThreadPool:0" (ID 124) failed to shut down`

Here's the log

[Log.txt](https://github.com/user-attachments/files/18086831/Log.txt)

**Comment by feserr** [comment]
Lets move this outside of this as it will be easier. My discord id is: @reisor777 (I will remove this comment once you add me)

**Comment by feserr** [comment]
The issue that @RubenPineda had was caused because `.env` was missing. This caused no server port was set and Steam failed to initialise if the port is empty.
